services:
  - type: web
    name: exam-sentry
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: AUTHORIZER_EMAIL
        value: faisaldiddi@gmail.com
      - key: SESSION_SECRET
        generateValue: true
      - key: APP_ENCRYPTION_KEY
        generateValue: true
